### ISSUE TITLE
13. Working Group Meeting

### ISSUE THREAD

**Issue by ghost** [Simsso/NIPS-2018-Adversarial-Vision-Challenge#56]
Date: 3. Oct 2018
_(aka. honeymoon)_

@doktorgibson
- [x] enablement tools #35
- [x] get [`avc-test-model`](https://gitlab.crowdai.org/florianpfisterer/adversarial-net) to work (docs [here](https://gitlab.crowdai.org/adversarial-vision-challenge/nips18-avc-model-template?_ga=2.212156564.120093324.1536687690-483773514.1534753204))
- [x] training pipeline finalization #62 

@FlorianPfisterer 
- [x] read wikipage of training pipeline
- [x] develop #51 further (implement direct embedding value assignment + tests)
- [x] make ResNet submittable #61 

@Simsso 
- [x] read wikipage of training pipeline
- [x] develop #51 further (in particular profiling #58)
- [x] logger class #60 
- [x] virtual batch sizes #64 
- [x] dotp norm order #63
