### ISSUE TITLE
VQ Profiling

### ISSUE THREAD

**Issue by Simsso** [Simsso/NIPS-2018-Adversarial-Vision-Challenge#58]
Memory and performance profiling of the VQ layer code (branch [`vq-layer`](https://github.com/Simsso/NIPS-2018-Adversarial-Vision-Challenge/tree/vq-layer)).

* [x] Investigate how the memory consumption changes depending on (batch size, vector size, embedding space size)
* [ ] Familiarize with [profiling tools](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/profiler/README.md)
* [x] Assess development of a C++ op that's more efficient
