### ISSUE TITLE
14. Working Group Meeting

### ISSUE THREAD

**Issue by Simsso** [Simsso/NIPS-2018-Adversarial-Vision-Challenge#71]
_aka: "ramping up to 200%"_
![image](https://user-images.githubusercontent.com/6556307/46421027-92803200-c731-11e8-8336-57a3fab3cffd.png)

Date: 15. Oct 2018

### Assignments

@doktorgibson 
* [ ] TRAINING ENABLEMENT TOOLS #11 

@simsso
* [ ] 'cos' similarity #63 
* [ ] structured tests #75
* [x] investigate issues with wavy accuracy patterns and low validation accuracy --> https://github.com/Simsso/NIPS-2018-Adversarial-Vision-Challenge/commit/0f90b239b2ed1455ce4f400f0d91f793f5bb12ae
* [x] fix vq-layer replacement & virtual batches #70 --> PR #79 
* [x] experiment with parallel VQ layers --> [submission](https://gitlab.crowdai.org/timodenk/vq-resnet/issues/6)
* [x] experiment with different gradient settings (skip gradient, normal, no gradient)
* [ ] experiment and implement with quantization along the spatial dimension (e.g. patches of 3x3) and a single embedding space for each channel
* [x] clean-up branch mess and hot-fixes (listed [here](https://github.com/Simsso/NIPS-2018-Adversarial-Vision-Challenge/issues/56#issuecomment-426675664)) PR #76 

@FlorianPfisterer 
* [ ] structured tests #75: find out stddev and mean of inputs + wiki entry
* [x] submission of VQResNet with checkpoint that achieves > 50% accuracy

### Discussion Points
* whether to pursue the VQ approach despite its disillusioning results; noting that there are ideas #78 
* financing (since we ran out of GCP credit)
