### ISSUE TITLE
20. Working Group Meeting

### ISSUE THREAD

**Issue by FlorianPfisterer** [Simsso/NIPS-2018-Adversarial-Vision-Challenge#96]
Date: 31. Oct 2018
### Tasks

* [x] Create all-variables saver @FlorianPfisterer 
* [ ] Provide .mat-files for all layers / dimensions as listed in #92 @FlorianPfisterer 
* [x] Implement grid search algorithm for hyper-parameter tuning (#92) @Simsso  + @FlorianPfisterer 
* [ ] Submit best configuration(s) @Simsso  + @FlorianPfisterer
